# Generated by Django 4.2.28 on 2026-02-15 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antispam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_access', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
