# Generated by Django 4.2.28 on 2026-02-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antispam', '0002_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='meta',
            field=models.JSONField(default=dict),
        ),
    ]
