# Generated by Django 4.0.10 on 2024-03-07 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('juntagrico', '0039_alter_activityarea_options_alter_member_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=30)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juntagrico.job', verbose_name='Job')),
            ],
            options={
                'verbose_name': 'Zugangsinfo',
                'verbose_name_plural': 'Zugangsinfos',
            },
        ),
        migrations.AddConstraint(
            model_name='accessinformation',
            constraint=models.UniqueConstraint(fields=('job', 'name'), name='unique job name'),
        ),
    ]
