# Generated by Django 4.2.17 on 2025-06-17 17:11

from django.db import migrations, models
import django.db.models.deletion
import juntagrico_mailqueue.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('subject', models.TextField()),
                ('body', models.TextField()),
                ('from_email', models.TextField()),
                ('to', models.JSONField(blank=True, default=list)),
                ('cc', models.JSONField(blank=True, default=list)),
                ('alternatives', models.JSONField(blank=True, default=list)),
                ('attachments', models.JSONField(blank=True, decoder=juntagrico_mailqueue.utils.AttachmentDecoder, default=list, encoder=juntagrico_mailqueue.utils.AttachmentEncoder)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('reply_to', models.JSONField(blank=True, default=list)),
                ('failed', models.BooleanField(default=False)),
                ('last_error', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='juntagrico_mailqueue.emailmessage')),
            ],
        ),
    ]
