# Generated by Django 2.0.2 on 2018-11-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico_crowdfunding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingproject',
            name='vocabulary_confirmOrder',
            field=models.TextField(blank=True, null=True, verbose_name='Formular: Kauf bestätigen'),
        ),
        migrations.AlterField(
            model_name='fundingproject',
            name='vocabulary_confirmOrderButton',
            field=models.CharField(max_length=200, verbose_name='Formular: Button Verbindlich bestätigen'),
        ),
        migrations.AlterField(
            model_name='fundingproject',
            name='vocabulary_thankYouMessage',
            field=models.TextField(blank=True, null=True, verbose_name='Text: Dankeschön'),
        ),
        migrations.AlterField(
            model_name='fundingproject',
            name='vocabulary_whoIsSponsor',
            field=models.TextField(blank=True, null=True, verbose_name='Formular: Patenschaftsnennung'),
        ),
    ]
