# Generated by Django 2.0.2 on 2018-11-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico_crowdfunding', '0002_auto_20181124_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingproject',
            name='vocabulary_confirmOrderButton',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Formular: Button Verbindlich bestätigen'),
        ),
    ]
