# Generated by Django 3.0.8 on 2020-09-18 19:00

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('juntagrico', '0026_auto_20200710_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(blank=True, help_text='Direktlink zu einem Bild', null=True, verbose_name='Bild-URL')),
                ('learn', ckeditor.fields.RichTextField(blank=True, help_text='Was kann das Mitglied in dieser Gruppe lernen? Welche Kenntnisse werden vorausgesetzt?', max_length=1500, null=True, verbose_name='Lernen / Vorkenntnisse')),
                ('introduction', ckeditor.fields.RichTextField(blank=True, help_text='Ist eine Einführung nötig?', max_length=1000, null=True, verbose_name='Einführung')),
                ('minimum_size', models.PositiveSmallIntegerField(default=1, verbose_name='Mindestgrösse')),
                ('target_size', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Wunschgrösse')),
                ('wanted', models.CharField(choices=[('no', 'Nein'), ('yes', 'Ja'), ('urgent', 'Dringend')], default='no', max_length=256, verbose_name='Interessierte Gesucht?')),
                ('wanted_for', models.CharField(blank=True, default='', help_text='Wofür genau werden Interessierte gesucht? (optional)', max_length=300, null=True, verbose_name='Interessierte Gesucht für')),
                ('group_extras', ckeditor.fields.RichTextField(blank=True, help_text='Weitere Informationen zur Gruppe und deren Mitglieder', max_length=1000, null=True, verbose_name='Gruppe / Mitglieder')),
                ('clothing', ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True, verbose_name='Kleidung')),
                ('season', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Januar'), (2, 'Februar'), (3, 'März'), (4, 'April'), (5, 'Mai'), (6, 'Juni'), (7, 'Juli'), (8, 'August'), (9, 'September'), (10, 'Oktober'), (11, 'November'), (12, 'Dezember')], max_length=26, null=True, verbose_name='Saison')),
                ('flexible', models.BooleanField(default=False, help_text='Können eingeführte Mitglieder, jederzeit selbständig Einsätze leisten?', verbose_name='Einsätze Flexibel möglich?')),
                ('alone', models.BooleanField(default=False, verbose_name='Einsätze alleine möglich?')),
                ('in_groups', models.BooleanField(default=False, verbose_name='Einsätze in Gruppen möglich?')),
                ('days', models.CharField(blank=True, help_text='Welche Tage der Woche gibt es Einsätze?', max_length=100, null=True, verbose_name='Tage')),
                ('jobs_more', ckeditor.fields.RichTextField(blank=True, help_text='Was muss für den Einsatz sonst noch beachtet werden?', max_length=1000, null=True, verbose_name='Mehr Einsatzdetails')),
                ('children', ckeditor.fields.RichTextField(blank=True, help_text='Falls ja, unter welchen Bedingungen. Falls nein, warum nicht?', max_length=500, null=True, verbose_name='Kinderbegleitung Möglich?')),
                ('email', models.EmailField(blank=True, help_text='E-Mail-Verteiler der Gruppe (falls vorhanden). Wenn leer wird Koordinations-E-Mail angezeigt.', max_length=254, null=True, verbose_name='Gruppen-E-Mail')),
                ('chat', models.URLField(blank=True, help_text='Link zu Chat der Gruppe in Telegram oder Whatsapp etc.', null=True, verbose_name='Gruppen-Chat-Link')),
                ('other_communication', models.CharField(blank=True, help_text='Andere Links oder Beschreibungen, wie Mitglieder interagieren können.', max_length=200, null=True, verbose_name='Andere Kommunikationsmethoden')),
                ('activity_area', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='juntagrico.ActivityArea', verbose_name='Tätigkeitsbereich')),
            ],
        ),
    ]
