# Generated by Django 3.0.8 on 2020-09-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityprofile',
            name='image_credits',
            field=models.CharField(blank=True, help_text='Falls für die Verwendung des Bilds eine Namensnennung erforderlich ist', max_length=100, null=True, verbose_name='Bild-Namensnennung'),
        ),
        migrations.AddField(
            model_name='activityprofile',
            name='image_credits_url',
            field=models.URLField(blank=True, help_text='Link zur Lizenz des Bilds (wenn erforderlich)', null=True, verbose_name='Bild-Namensnennung-URL'),
        ),
        migrations.AlterField(
            model_name='activityprofile',
            name='wanted',
            field=models.CharField(choices=[('no', 'Nein'), ('yes', 'Ja'), ('urgent', 'Dringend')], default='no', max_length=10, verbose_name='Interessierte Gesucht?'),
        ),
    ]
