# Generated by Django 3.0.8 on 2020-09-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityprofile', '0002_auto_20200918_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityprofile',
            name='active_members',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Anzahl aktive Mitglieder'),
        ),
    ]
