# Generated by Django 5.2.10 on 2026-01-23 22:15

import djrichtextfield.models
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityprofile', '0003_activityprofile_active_members'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityprofile',
            options={'verbose_name': 'Steckbrief', 'verbose_name_plural': 'Steckbriefe'},
        ),
        migrations.AlterField(
            model_name='activityprofile',
            name='children',
            field=djrichtextfield.models.RichTextField(blank=True, help_text='Falls ja, unter welchen Bedingungen. Falls nein, warum nicht?', max_length=500, null=True, verbose_name='Kinderbegleitung Möglich?'),
        ),
        migrations.AlterField(
            model_name='activityprofile',
            name='clothing',
            field=djrichtextfield.models.RichTextField(blank=True, max_length=1000, null=True, verbose_name='Kleidung'),
        ),
        migrations.AlterField(
            model_name='activityprofile',
            name='group_extras',
            field=djrichtextfield.models.RichTextField(blank=True, help_text='Weitere Informationen zur Gruppe und deren Mitglieder', max_length=1000, null=True, verbose_name='Gruppe / Mitglieder'),
        ),
        migrations.AlterField(
            model_name='activityprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='activityprofile',
            name='introduction',
            field=djrichtextfield.models.RichTextField(blank=True, help_text='Ist eine Einführung nötig?', max_length=1000, null=True, verbose_name='Einführung'),
        ),
        migrations.AlterField(
            model_name='activityprofile',
            name='jobs_more',
            field=djrichtextfield.models.RichTextField(blank=True, help_text='Was muss für den Einsatz sonst noch beachtet werden?', max_length=1000, null=True, verbose_name='Mehr Einsatzdetails'),
        ),
        migrations.AlterField(
            model_name='activityprofile',
            name='learn',
            field=djrichtextfield.models.RichTextField(blank=True, help_text='Was kann das Mitglied in dieser Gruppe lernen? Welche Kenntnisse werden vorausgesetzt?', max_length=1500, null=True, verbose_name='Lernen / Vorkenntnisse'),
        ),
        migrations.AlterField(
            model_name='activityprofile',
            name='season',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Januar'), ('2', 'Februar'), ('3', 'März'), ('4', 'April'), ('5', 'Mai'), ('6', 'Juni'), ('7', 'Juli'), ('8', 'August'), ('9', 'September'), ('10', 'Oktober'), ('11', 'November'), ('12', 'Dezember')], max_length=1000, null=True, verbose_name='Saison'),
        ),
    ]
