# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: juntagrico-ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, release_* ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: .
      DJANGO_SETTINGS_MODULE: mehalsgmues.settings
      JUNTAGRICO_SECRET_KEY: fake
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: install dependencies
      run: |
        pip install --upgrade -r requirements-local.txt
    - name: run tests
      run: |
        python -m django makemigrations --noinput
        python -m django collectstatic -c --noinput
        python -m manage test
    - name: flake 8
      run: |
        flake8 --count --ignore E501 mehalsgmues
        flake8 --count --ignore E501 test